haproxy:
  listen_port: 6443
  backend_port: 6443

keepalive:
  health_check:
    script_name: check_apiserver.sh
    interval: 3
    weight: -10
    fall: 5
    rise: 2
    timeout: 10
  config_path: /etc/keepalived
  virtual_ip: 192.168.29.100
  interface: eth1
  virtual_router_id: 51
  advert_int: 1
  auth_pass: "my_secure_password"

keepalive_configure: true
keepalive_verify: false
keepalive_failover: false
  