$ANSIBLE_VAULT;1.1;AES256
39393937666561383236646162643931643936633361656132383334663437366130306634626431
3030383039306333353438356461666434623261616533650a353234306133646463316566313132
66346331626131363063663432656531323739306436383739303633316262346263633464353162
6633366236333637310a313363303834336334643438623334333164656366613261623431356531
31303932383264383563663733363564633431663039323134663233313864383035333332363561
3361613533343430323061353264623132643535353766323831
