---
galaxy_info:
  role_name: keepalive
  author: Mahin Raza
  description: Configure and validate HA load balancers using Keepalived (VRRP)
  license: MIT
  min_ansible_version: "2.12"

  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - focal

  galaxy_tags:
    - keepalived
    - vrrp
    - ha
    - loadbalancer
    - kubernetes
    - highavailability

dependencies: []
