---
galaxy_info:
  role_name: kubernetes
  author: Mahin Raza
  description: >
    Installs Kubernetes components (kubeadm, kubelet, kubectl)
    along with CRI-O runtime on Debian/Ubuntu systems.
    Adds official repositories, installs packages,
    holds Kubernetes versions, and verifies installation.

  company: personal-lab
  license: MIT

  min_ansible_version: "2.14"

  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - focal

  galaxy_tags:
    - kubernetes
    - kubeadm
    - kubelet
    - kubectl
    - crio
    - container-runtime
    - devops
    - cluster

dependencies: []
