apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration

clusterName: kubernetes
kubernetesVersion: v1.35.0

# Load balancer / VIP (MANDATORY for HA)
controlPlaneEndpoint: "192.168.29.81:6443"

networking:
  podSubnet: 192.168.0.0/16
  serviceSubnet: 10.96.0.0/16

# External etcd
etcd:
  external:
    endpoints:
      - https://etcdone:2379
      - https://etcdtwo:2379
      - https://etcdthree:2379
    caFile: /etc/kubernetes/pki/etcd/ca.pem
    certFile: /etc/kubernetes/pki/etcd/apiserver-etcd-client.pem
    keyFile: /etc/kubernetes/pki/etcd/apiserver-etcd-client-key.pem

# API server certificate SANs
apiServer:
  certSANs:
    - "192.168.29.81" #<LOAD_BALANCER_PRIVATE_IP>
    - "masterone"
    - "192.168.29.51"
    - "127.0.0.1"
    - "kubernetes"
    - "kubernetes.default"
    - "kubernetes.default.svc"
    - "kubernetes.default.svc.cluster.local"

    #- "" #<HAPROXY_PUBLIC_IP>

---
apiVersion: kubeadm.k8s.io/v1beta4
kind: InitConfiguration

localAPIEndpoint:
  advertiseAddress: 192.168.29.51   # MASTERONE IP
  bindPort: 6443

nodeRegistration:
  name: masterone
  criSocket: unix:///var/run/crio/crio.sock

---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration

serializeImagePulls: false
maxParallelImagePulls: 10

evictionHard:
  memory.available: "200Mi"
  nodefs.available: "20%"
  nodefs.inodesFree: "5%"
