---
- name: Deploy HAProxy config
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'
  notify: Restart haproxy
  become: true

- name: Validate HAProxy config
  command: haproxy -c -f /etc/haproxy/haproxy.cfg
  register: haproxy_config_check
  failed_when: haproxy_config_check.rc != 0
  become: true

- name: Enable HAProxy
  systemd:
    name: haproxy
    enabled: true
    state: started
  become: true
