---
galaxy_info:
  role_name: etcd
  author: Mahin Raza
  description: Configure a secure external etcd cluster for Kubernetes HA setup
  company: personal-lab
  license: MIT
  min_ansible_version: "2.14"

  platforms:
    - name: Ubuntu
      versions:
        - jammy

  galaxy_tags:
    - etcd
    - kubernetes
    - ha
    - clustering
    - tls

dependencies: []
