---
galaxy_info:
  role_name: haproxy
  author: Mahin Raza
  description: Configure HAProxy load balancers for Kubernetes HA control plane
  company: personal-lab
  license: MIT
  min_ansible_version: "2.14"

  platforms:
    - name: Ubuntu
      versions:
        - jammy

  galaxy_tags:
    - haproxy
    - loadbalancer
    - kubernetes
    - ha
    - tcp

dependencies: []
