- name: Installing python3-pip package on masterone
  ansible.builtin.package:
    name: python3-pip
    state: present
    
- name: Install required packages for kubernetes on masterone
  pip:
    name:
      - kubernetes
    state: present

